export default [
  {
    image: "/work/WEBSITE ART 16 Hudson  KT 060222 DEVELOPMENT.png",
    branded: "true",
    voice: "true",
    originals: "true",
    series: "true",
    features: "true",
    featuresDesc: "testing",
    seriesDesc: "series test",
    key: 1,
    category: "features, voice, series",
  },
  {
    image:
      "/work/WEBSITE ART A Stork's Journey 2 CK 060822 VOICE FEATURE DEVELOPMENT.png",
    branded: "true",
    voice: "true",
    originals: "true",
    series: "true",
    features: "false",
    seriesDesc: "testing this",
    key: 2,
    category: "features, voice, series",
  },
  {
    image:
      "/work/WEBSITE ART A Stork's Journey 2 CK 060822 VOICE FEATURE DEVELOPMENT.png",
    branded: "true",
    voice: "true",
    originals: "true",
    series: "true",
    features: "false",
    seriesDesc: "testing this",
    key: 3,
    category: "branded, series",
  },
  {
    image:
      "/work/WEBSITE ART A Stork's Journey 2 CK 060822 VOICE FEATURE DEVELOPMENT.png",
    branded: "true",
    voice: "true",
    originals: "true",
    series: "true",
    features: "false",
    seriesDesc: "testing this",
    key: 4,
    category: "originals, voice, series",
  },
  {
    image:
      "/work/WEBSITE ART A Stork's Journey 2 CK 060822 VOICE FEATURE DEVELOPMENT.png",
    branded: "true",
    voice: "true",
    originals: "true",
    series: "true",
    features: "true",
    seriesDesc: "testing this",
    key: 5,
    category: "features, voice, series",
  },
  {
    image:
      "/work/WEBSITE ART A Stork's Journey 2 CK 060822 VOICE FEATURE DEVELOPMENT.png",
    branded: "true",
    voice: "true",
    originals: "true",
    series: "true",
    features: "false",
    seriesDesc: "testing this",
    key: 6,
    category: "features, voice, series, branded",
  },
  {
    image:
      "/work/WEBSITE ART A Stork's Journey 2 CK 060822 VOICE FEATURE DEVELOPMENT.png",
    branded: "true",
    voice: "true",
    originals: "true",
    series: "true",
    features: "false",
    seriesDesc: "testing this",
    key: 7,
    category: "voice, series",
  },
];
